# Generated by Django 3.1.7 on 2021-06-07 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=255, unique=True, verbose_name='句子内容')),
                ('translation', models.CharField(blank=True, max_length=255, null=True, verbose_name='句子翻译')),
            ],
            options={
                'verbose_name': '句子内容',
                'verbose_name_plural': '句子管理',
                'db_table': 'sentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'translate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.CharField(blank=True, max_length=10, null=True, verbose_name='单词词性')),
                ('translation', models.CharField(max_length=100, verbose_name='单词含义')),
            ],
            options={
                'verbose_name': '词汇翻译',
                'verbose_name_plural': '词汇翻译管理',
                'db_table': 'translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=40, unique=True, verbose_name='单词名称')),
                ('levels', models.CharField(blank=True, choices=[('', '空'), ('level_1', '等级一'), ('level_2', '等级二'), ('level_3', '等级三'), ('level_4', '等级四'), ('level_5', '等级五')], max_length=10, null=True, verbose_name='单词等级')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词管理',
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.word')),
            ],
            options={
                'db_table': 'Instance',
            },
        ),
    ]
