# Generated by Django 3.1.7 on 2021-04-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=255, unique=True)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sentence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'translate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.CharField(blank=True, max_length=10, null=True)),
                ('translation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=40, unique=True)),
                ('levels', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
    ]
